version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule: { interval: weekly }
    groups:
      aspnetcore: { patterns: ["Microsoft.AspNetCore.*", "Microsoft.EntityFrameworkCore.*"] }
      masstransit: { patterns: ["MassTransit*"] }
  - package-ecosystem: npm
    directory: "/client"
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: "/infra"
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
